// Generated by dts-bundle v0.7.3
// Dependencies for this module:
//   ../react
//   ../redux

import * as React from 'react';
import { Action, Dispatch, ActionCreator } from 'redux';
import { Reducer } from 'redux';

/** @module Controller:index */

/** @module Model:index */

/** @module Selector:index */

/** @module Types:index */

/** @internal */
export interface TemplateProps {
    color: BsUiModelTemplatePropertyColorState;
    onInitModel: () => any;
    onResetModel: () => any;
    onUpdateTemplateColorAsync: () => any;
    onUpdateTemplateColorBatch: () => any;
}
export class TemplateComponent extends React.Component<TemplateProps> {
    componentDidMount(): void;
    componentWillUnmount(): void;
    renderComponent(): JSX.Element;
    renderModel(): JSX.Element;
    renderController(): JSX.Element;
    renderType(): JSX.Element;
    renderError(): JSX.Element;
    renderHeader(): JSX.Element;
    renderBody(): JSX.Element;
    render(): JSX.Element;
}
export const Template: React.ComponentClass<Pick<TemplateProps, never> & undefined> & {
    WrappedComponent: React.ComponentType<TemplateProps>;
};

export const initModel: () => BsUiModelThunkAction<Promise<any>>;
export const resetModel: () => BsUiModelThunkAction<BsUiModelAction<null>>;

/** @private */
export const updateTemplateColorAsync: () => BsUiModelThunkAction<Promise<any>>;
/** @private */
export const updateTemplateColorBatch: () => BsUiModelThunkAction<BsUiModelBatchAction>;

/** @module Model:base */
/** @private */
export const BSUIMODEL_BATCH = "BSUIMODEL_BATCH";
/** @private */
export const BSUIMODEL_REHYDRATE = "BSUIMODEL_REHYDRATE";
/** @private */
export const BSUIMODEL_RESET = "BSUIMODEL_RESET";
/** @private */
export type BsUiModelDispatch = Dispatch<BsUiModelState>;
/** @private */
export interface BsUiModelBaseAction extends Action {
    type: string;
    payload: {};
    error?: boolean;
    meta?: {};
}
/** @private */
export interface BsUiModelAction<T> extends BsUiModelBaseAction {
    payload: T;
}
/** @private */
export type BsUiModelActionCreator<T> = ActionCreator<BsUiModelAction<T>>;
/** @private */
export type BsUiModelThunkAction<T> = (dispatch: BsUiModelDispatch, getState: () => BsUiModelState, extraArgument: undefined) => T;
/** @private */
export const bsUiModelBatchAction: (action: BsUiModelBaseAction[]) => BsUiModelBatchAction;
/** @private */
export interface BsUiModelBatchAction extends Action {
    type: string;
    payload: BsUiModelBaseAction[];
}
/** @private */
export interface RehydrateBsUiModelParams {
    newBsUiModelState: BsUiModelState;
}
/** @private */
export type RehydrateBsUiModelAction = BsUiModelAction<RehydrateBsUiModelParams>;
export const bsUiModelRehydrateModel: (bsUiModelState: BsUiModelState) => BsUiModelAction<RehydrateBsUiModelParams>;
/** @private */
export type ResetBsUiModelAction = BsUiModelAction<null>;
export const bsUiModelResetModel: () => BsUiModelAction<null>;

/** @module Model:base */
export type BsUiReducer = Reducer<BsUiModelState>;
export const bsUiModelReducer: BsUiReducer;
export const isValidBsUiModelState: (state: any) => boolean;
export const isValidBsUiModelStateShallow: (state: any) => boolean;

/** @private */
export const templateReducer: (state: BsUiModelTemplateState, action: BsUiModelBatchAction) => BsUiModelTemplateState;
/** @private */
export const isValidTemplateState: (state: any) => boolean;
/** @private */
export const isValidTemplateStateShallow: (state: any) => boolean;

/** @private */
export const BSUIMODEL_UPDATE_TEMPLATE_PROPERTY: string;
/** @private */
export const BSUIMODEL_RESET_TEMPLATE_PROPERTY: string;
/** @private */
export type UpdateTemplatePropertyAction = BsUiModelAction<Partial<BsUiModelTemplatePropertyState>>;
/** @private */
export type ResetTemplatePropertyAction = BsUiModelAction<null>;
/** @private */
export const bsUiModelResetTemplateProperty: () => BsUiModelAction<null>;
/** @private */
export const bsUiModelUpdateTemplateColor: (color: BsUiModelTemplatePropertyColorState) => BsUiModelAction<Partial<BsUiModelTemplatePropertyState>>;
/** @private */
export const templatePropertyDefault: BsUiModelTemplatePropertyState;
/** @private */
export const templatePropertyReducer: (state: BsUiModelTemplatePropertyState | undefined, {type, payload}: BsUiModelAction<null> | BsUiModelAction<RehydrateBsUiModelParams> | BsUiModelAction<Partial<BsUiModelTemplatePropertyState>>) => BsUiModelTemplatePropertyState;
/** @private */
export const isValidColor: (state: any) => boolean;
/** @private */
export const isValidTemplatePropertyState: (state: any) => boolean;
/** @private */
export const isValidTemplatePropertyStateShallow: (state: any) => boolean;

/** @module Selector:base */
/** @private */
export const bsUiModelFilterBaseState: (state: any) => BsUiModelState;
/** @private */
export const bsUiModelGetBaseState: (state: BsUiModelState) => BsUiModelState;

/** @private */
export const bsUiModelGetTemplateState: (state: BsUiModelState) => BsUiModelTemplateState;

/** @private */
export const bsUiModelGetTemplatePropertyState: (state: BsUiModelState) => BsUiModelTemplatePropertyState;
/** @private */
export const bsUiModelGetTemplatePropertyColorState: (state: BsUiModelState) => BsUiModelTemplatePropertyColorState;

/** @module Types:base */
/** @private */
export type DeepPartial<T> = {
    [P in keyof T]?: DeepPartial<T[P]>;
};
/** @private */
export interface BsUiModelState {
    template: BsUiModelTemplateState;
}
/** @private */
export const createModel: (template: BsUiModelTemplateState) => BsUiModelState;

/** @module Types:template */
/** @private */
export interface BsUiModelTemplateState {
    readonly property: BsUiModelTemplatePropertyState;
}
/** @private */
export const createTemplate: (property: BsUiModelTemplatePropertyState) => BsUiModelTemplateState;

/** @private */
export interface BsUiModelTemplatePropertyColorState {
    a: number;
    r: number;
    g: number;
    b: number;
}
/** @private */
export interface BsUiModelTemplatePropertyState {
    color: BsUiModelTemplatePropertyColorState;
}
/** @private */
export const createTemplateProperty: (color: BsUiModelTemplatePropertyColorState) => BsUiModelTemplatePropertyState;
/** @private */
export const createBsColor: (r: number, g: number, b: number, a: number) => BsUiModelTemplatePropertyColorState;

export enum BsUiErrorType {
    unknownError = 0,
    unexpectedError = 1,
    invalidParameters = 2,
    invalidOperation = 3,
    apiError = 4,
    invalidModel = 5,
}
export class BsUiError extends Error {
    name: string;
    type: BsUiErrorType;
    constructor(type: BsUiErrorType, reason?: string);
}
export function isBsUiError(error: Error): error is BsUiError;

